# Site settings
title:       Peter Goldsborough
email:       peter@goldsborough.me
author:      Peter Goldsborough
baseurl:     ""
url:         "http://www.goldsborough.me"
date_format: "%b %-d, %Y"
description: A blog on computer science, artificial intelligence and the excitement of life.

# Jekyll settings
plugins:
  - jekyll-paginate
  - jekyll-gist

# Google services
google_analytics: UA-75082316-1
google_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footer:    true
show_rss:             true
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax:       true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: petergoldsborough

# Social icons
github_username: goldsborough
stackoverflow_id: 1810440
twitter_username: pegoldsborough
linkedin_username: petergoldsborough
bitcoin_url:
paypal_url: "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=SGAMY6ME8YMSC"

# Post sharing icons
share_text:
show_sharing_icons: true
share_facebook: 	true
share_twitter: 		true
share_googleplus: 	true
share_linkedin: 	true
share_tumblr: 		true
share_reddit: 		true
share_stumbleupon:	true
share_hackernews: 	true

# Build settings
markdown:     kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink:    pretty
paginate:     8
sass:
  compressed: true

# Additional settings
include: ['_pages']
